---
- name: add virtualbox rpm key
  become: yes
  become_user: root
  rpm_key:
    key: '{{virtualbox_key_url}}'
    state: present

- name: add virtualbox yum repo
  become: yes
  become_user: root
  yum_repository:
    name: virtualbox
    description: VirtualBox YUM Repository
    baseurl: '{{virtualbox_yum_baseurl}}'
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes
    repo_gpgcheck: yes

